name: Deploy Lambda Function
on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: pip install flake8
      - name: Lint with flake8
        run: |
            cd function
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi 
      - name: Zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read
    steps:
      - name: download artifact 
        uses: actions/download-artifact@v2 
        with:
          name: zipped-bundle
      - name: Configure AWS credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::605151010092:role/github-actions-role-s3-lambda 
          aws-region: ap-southeast-2
      - name: upload to S3 
        run: aws s3 cp ${{ github.sha }}.zip s3://ggburton-github-actions-test/${{ github.sha }}.zip
  
  deploy:   
    runs-on: ububuntu-latest 
    needs: upload
    permissions:
      id-token: write 
      contents: read
    steps:
      - name: Configure AWS credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::605151010092:role/github-actions-role-s3-lambda 
          aws-region: ap-southeast-2
      - run: |
          aws lambda unpdate-function-code \
            --function-name test-function \
            --s3-bucket ggburton-github-actions-test \
            --s3-key ${{ github.sha }}.zip \
            --publish
